version: '3.5'

services:
 
  wazuh:
    image: wazuh/wazuh:3.13.1_7.8.0
    hostname: wazuh-manager
    restart: always
    ports:
      - "1516:1516"
      - "514:514/udp"
      - "1514/udp"
      - "1515"
      - "55000:55000"
    command:
      - '/var/ossec/bin/ossec-control restart'
    volumes:
      - ./master_configuration.sh:/entrypoint-scripts/master_configuration.sh   
      - ./wazuhdata/:/var/ossec/data/:rw
        #      - ./ossec.conf/:/var/ossec/etc/ossec.conf:rw
  

  wazuh-worker:
    image: wazuh/wazuh:3.13.1_7.8.0
    hostname: wazuh-worker
    restart: always
    ports:
      - "1514/udp"
      - "514/udp"
      - "1515"
      - "1516"
      - "55000"
    volumes:
      - ./worker_configuration.sh:/entrypoint-scripts/worker_configuration.sh



  elasticsearch:
    image: wazuh/wazuh-elasticsearch:3.13.1_7.8.0
    hostname: elasticsearch
    restart: always
    ports:
      - "9200:9200"
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - ELASTIC_CLUSTER=true
      - CLUSTER_NODE_MASTER=true
      - CLUSTER_MASTER_NODE_NAME=es01
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    image: wazuh/wazuh-kibana:3.13.1_7.8.0
    hostname: kibana
    restart: always
    depends_on:
      - elasticsearch
    links:
      - elasticsearch:elasticsearch
      - wazuh:wazuh

  nginx:
    image: wazuh/wazuh-nginx:3.13.1_7.8.0
    hostname: nginx
    restart: always
    environment:
      - NGINX_PORT=443
      - NGINX_CREDENTIALS
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - kibana
    links:
      - kibana:kibana

  postfix:
    image: eeacms/postfix:2.10-3.5
    hostname: wazuh-smtp
    restart: always
    environment:
      - MTP_RELAY=${MTP_RELAY}
      - MTP_PORT=${MTP_PORT}
      - MTP_USER=${MTP_USER}
      - MTP_PASS=${MTP_PASS}
      - MTP_HOST=${MTP_HOST}      
    ports:
      - "587:587"

  load-balancer:
    image: nginx
    ports:
      - "1514:1514/udp"
      - "1515:1515"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    command: [nginx-debug, '-g', 'daemon off;']
